### ISSUE TITLE
Iterative Deeping Search Stops at level 2?

### ISSUE THREAD

**Issue by SandeepaDilshanAlagiyawanna** [Ahmed712441/AI-Graph-Search#1]
hi, In my state space, Iterative Deeping Search Stops at level 2 without finding the goal. Why ?

**Comment by Ahmed712441** [comment]
Hi , Can you save your graph and send it to me (.gtxt file) so I can know more about your issue?

**Comment by SandeepaDilshanAlagiyawanna** [comment]
It was solved. Thank you
